#!/bin/bash

#var
plasma="plasma-meta konsole kwrite dolphin ark plasma-workspace egl-wayland"
baseapps="git curl mc htop fastfetch timeshift p7zip"
kdeapps="filelight ark dolphin dolphin-plugins elisa gwenview kate kcalc kcron kdeconnect kdenetwork-filesharing kdenlive kdialog kfind kgpg kjournald krdc krfb ksystemlog kwalletmanager okular partitionmanager signon-kwallet-extension spectacle" 
fonts="terminus-font cantarell-fonts freetype noto-fonts noto-fonts-cjk noto-fonts-extra ttf-bitstream-vera ttf-dejavu ttf-liberation ttf-opensans"
asianfonts="adobe-source-han-sans-cn-fonts adobe-source-han-sans-jp-fonts adobe-source-han-sans-kr-fonts adobe-source-han-sans-otc-fonts adobe-source-han-sans-tw-fonts adobe-source-han-serif-cn-fonts adobe-source-han-serif-jp-fonts adobe-source-han-serif-kr-fonts adobe-source-han-serif-otc-fonts adobe-source-han-serif-tw-fonts"
power="power-profiles-daemon upower"
virtualization="virt-manager qemu-full"
networks="openvpn networkmanager-openvpn sshfs bridge-utils dnsmasq"
gaming="steam mangohud goverlay gamemode gamescope"
social="telegram-desktop discord"

cd $HOME

sudo pacman -S base-devel --noconfirm
sudo pacman -S $baseapps --noconfirm
sudo pacman -S $kdeapps --noconfirm
sudo pacman -S $networks --noconfirm
sudo pacman -S $virtualization --noconfirm
sudo pacman -S $power --noconfirm

git clone https://aur.archlinux.org/yay-bin.git
cd $HOME/yay-bin
makepkg -si
cd $HOME
rm -rf $HOME/yay-bin

yay -Syu google-chrome visual-studio-code-bin --noconfirm

sudo pacman -S $fonts --noconfirm
sudo pacman -S $asianfonts --noconfirm

sudo pacman -S $gaming --noconfirm
sudo pacman -S $social --noconfirm

sudo pacman -S flatpak flatpak-kcm --noconfirm

echo "set flatpak"
# sudo flatpak override --nosocket=wayland
flatpak -u override --filesystem=/usr/share/icons/:ro
flatpak -u override --filesystem=/home/$USER/.icons/:ro 
flatpak -u override --filesystem=xdg-config/gtk-3.0:ro
flatpak -u override --env=XCURSOR_PATH=~/.icons
flatpak -u override --env=XCURSOR_THEME=breeze
flatpak -u override --env=XCURSOR_SIZE=24

sudo setfont ter-v16b

sudo systemctl enable --now bluetooth

sudo systemctl enable --now sshd

sudo systemctl enable --now libvirtd.socket

fastfetch

