#!/bin/bash

sudo pacman -Syu git refind shim sbsigntools efibootmgr 

git clone https://aur.archlinux.org/preloader-signed.git
cd preloader-signed
makepkg -si --noconfirm
cd ..

git clone https://aur.archlinux.org/shim-signed.git
cd shim-signed
makepkg -si --noconfirm
cd ..

