#!/bin/bash

# Виконання скрипту для встановлення rEFInd та необхідних пакунків
# Виконувати виключно в Root

printf "Інсталяція пакунків...\n"

pacman -Syu refind shim sbsigntools efibootmgr

git clone https://aur.archlinux.org/preloader-signed.git
cd preloader-signed
makepkg -si --noconfirm
cd ..
rm -rf preloader-signed

git clone https://aur.archlinux.org/shim-signed.git
cd shim-signed
makepkg -si --noconfirm
cd ..
rm -rf shim-signed

printf "Інсталяція rEFInd...\n"

refind-install --preloader /usr/share/preloader-signed/PreLoader.efi 
refind-install --shim /usr/share/shim-signed/shimx64.efi --localkeys

sbsign --key /etc/refind.d/keys/refind_local.key --cert /etc/refind.d/keys/refind_local.crt --output /boot/vmlinuz-linux-zen /boot/vmlinuz-linux-zen

## Автоматичне підписування ядра при оновленні через hook
mkdir -p /etc/pacman.d/hooks
cat << EOF > /etc/pacman.d/hooks/99-refind.hook
[Trigger]
Type = Package
Operation = Upgrade
Target = linux-zen
[Action]
Description = Sign kernel for rEFInd...
When = PostTransaction
Exec = /usr/bin/sbsign --key /etc/refind.d/keys/refind_local.key --cert /etc/refind.d/keys/refind_local.crt --output /boot/vmlinuz-linux-zen /boot/vmlinuz-linux-zen
EOF